Repository Team-Daengnyang/moneynyang-client, pull requests merged in 2024-08, with the labels that each got.

#2 [FIX] css 초기 세팅 수정
  src/App.tsx
  src/assets/Login/loginImg.png
  src/assets/Login/loginLogo.png
  src/index.css
  src/pages/Login/login.tsx
Labels: FIX

#4 [FEAT] 회원가입 뷰 완료
  src/App.tsx
  src/assets/Login/kakao.png
  src/assets/Login/naver.png
  src/assets/Signup/check.png
  src/assets/Signup/picture.png
  src/assets/Signup/plus.png
  src/assets/Signup/success.png
  src/assets/leftAngle.png
  src/components/Button/index.tsx
  src/components/Topbar/index.tsx
  src/pages/Login/login.tsx
  src/pages/Signup/AccountCover.tsx
  src/pages/Signup/AccountRegistration.tsx
  src/pages/Signup/AnimalCheck.tsx
  src/pages/Signup/AnimalInfo.tsx
  src/pages/Signup/Selfauthentication.tsx
  src/pages/Signup/SignupSuccess.tsx
Labels: FEAT

#6 [FEAT] 메인페이지 화면 구성 및 navbar 컴포넌트 분리
  src/App.tsx
  src/assets/Main/animals.png
  src/assets/Main/bankbook.png
  src/assets/Main/footPrint.png
  src/assets/Main/mainLogo.png
  src/assets/Main/money.png
  src/assets/Main/moneyBag.png
  src/assets/Main/profile.png
  src/assets/Main/rightAngle.png
  src/assets/Main/shinhan.png
  src/assets/Navbar/card.png
  src/assets/Navbar/home0.png
  src/assets/Navbar/home1.png
  src/assets/Navbar/person0.png
  src/assets/Navbar/person1.png
  src/components/Navbar/index.tsx
  src/pages/Main/index.tsx
Labels: FEAT

#8 [FEATp 마이 페이지 뷰 개발
  src/App.tsx
  src/assets/Mypage/coin.png
  src/assets/Mypage/plus.png
  src/assets/Mypage/target.png
  src/assets/dogSample.jpg
  src/assets/rightAngle.png
  src/components/Navbar/index.tsx
  src/pages/Main/index.tsx
  src/pages/Mypage/Mypage.tsx
Labels: FEAT

#9 Feature/#3
  src/App.tsx
  src/assets/Invest/Money bag.png
  src/assets/icons/ChevronLeft.png
  src/assets/icons/Target.png
  src/assets/icons/blue home.png
  src/assets/icons/blue person.png
  src/assets/icons/blueCheck.png
  src/assets/icons/chevronDown.png
  src/assets/icons/chevronRight.png
  src/assets/icons/chevronUp.png
  src/assets/icons/creditcard.png
  src/assets/icons/darkgray chevronLeft.png
  src/assets/icons/gold coin.png
  src/assets/icons/gray home.png
  src/assets/icons/gray paw.png
  src/assets/icons/gray person.png
  src/assets/icons/ic_plus.png
  src/assets/icons/imagebox.png
  src/assets/icons/money bag.png
  src/assets/icons/trash.png
  src/assets/images/cat and dog.png
  src/assets/images/cat and dog2.png
  src/assets/images/creditcard.png
  src/assets/images/daengNyang.png
  src/assets/images/happy dog.png
  src/assets/images/img_4.png
  src/assets/images/img_7.png
  src/assets/images/money bag.png
  src/assets/images/money.png
  src/assets/images/paw print.png
  src/assets/images/sampleDog.jpg
  src/assets/images/shinhan.png
  src/assets/images/white pet.png
  src/components/Card/FinishedGoalCard.tsx
  src/components/Card/GoalCard.tsx
  src/pages/investPet/Complete.tsx
  src/pages/investPet/Deposit.tsx
  src/pages/investPet/InvestPet.tsx
  src/pages/investPet/SavingsGoal.tsx
  src/pages/investPet/TotalSpent.tsx
  src/routes/InvestPages.tsx
  tailwind.config.js
Labels: FEAT

#11 [FIX] 라우팅 방식 및 이미지 경로 수정
  .env
  src/App.tsx
  src/components/Topbar/index.tsx
  src/pages/Main/index.tsx
  src/pages/Signup/AccountCover.tsx
  src/pages/Signup/AccountRegistration.tsx
  src/pages/Signup/AnimalCheck.tsx
  src/pages/Signup/AnimalInfo.tsx
  src/pages/Signup/Selfauthentication.tsx
  src/pages/Signup/SignupSuccess.tsx
  src/routes/SignupPages.tsx
Labels: FIX

#13 [FEAT] 결제 페이지 완료
  src/App.tsx
  src/assets/Main/blueCheck.png
  src/components/Navbar/index.tsx
  src/pages/Main/index.tsx
  src/pages/Payment/PayComplete.tsx
  src/pages/Payment/PayMoney.tsx
  src/pages/Payment/Payment.tsx
  src/pages/Signup/AnimalCheck.tsx
  src/pages/Signup/AnimalInfo.tsx
  src/pages/Signup/SignupSuccess.tsx
  src/routes/PaymentPages.tsx
Labels: FEAT, 채린

#15 Feature/#14
  src/App.tsx
  src/assets/icons/Idea.png
  src/assets/icons/chevronRightWhite.png
  src/assets/images/coin.png
  src/assets/images/hanhwa.png
  src/components/Card/InsuranceCard.tsx
  src/pages/CashWalk/CashWalk.tsx
  src/pages/Main/index.tsx
  src/pages/insurance/Insurance.tsx
  src/pages/insurance/InsuranceDetail.tsx
  src/routes/CashWalkPages.tsx
  src/routes/InsurancePages.tsx
Labels: FEAT, 우영

#20 [FEAT] 거래 내역 조회 페이지 완료
  package-lock.json
  package.json
  src/App.tsx
  src/components/Topbar/index.tsx
  src/pages/Account/AccountInfo.tsx
  src/pages/Main/index.tsx
  src/routes/AccountPages.tsx
Labels: FEAT, 채린

#21 [FEAT] 반려동물에게 투자하기(2)
  README.md
  src/assets/icons/trash.png
  src/components/Card/FinishedGoalCard.tsx
  src/components/Card/GoalCard.tsx
  src/components/Card/InsuranceCard.tsx
  src/pages/CashWalk/CashWalk.tsx
  src/pages/Main/index.tsx
  src/pages/insurance/Insurance.tsx
  src/pages/insurance/InsuranceDetail.tsx
  src/pages/investPet/InvestPet.tsx
  src/pages/investPet/TotalSpent.tsx
  src/routes/InsurancePages.tsx
  src/routes/InvestPages.tsx
Labels: FEAT, 우영

#23 [FEAT] PWA 세팅
  index.html
  public/144.png
  public/192.png
  public/32.png
  public/48.png
  public/512.png
  public/72.png
  public/96.png
  public/manifest.json
  public/service-worker.js
  src/App.tsx
  src/assets/icons/chaticon.png
  src/assets/icons/send.png
  src/pages/ChatBot/ChatBot.tsx
  src/pages/Main/index.tsx
  src/serviceWorkerRegistration.js
Labels: FEAT, 우영

#26 [FEAT] 계좌 상세 페이지 완료
  package-lock.json
  package.json
  src/pages/Account/AccountData.tsx
  src/pages/Account/Chart.tsx
  src/routes/AccountPages.tsx
Labels: FEAT, 채린

#28 [FEAT] 캘린더, 보험상품 디테일 뷰 개발
  package-lock.json
  package.json
  src/assets/images/diary.png
  src/assets/images/pawCalendar.png
  src/pages/CashWalk/CalendarView.tsx
  src/pages/CashWalk/CashWalk.tsx
  src/pages/CashWalk/Write.tsx
  src/pages/CashWalk/styles.ts
  src/pages/Main/index.tsx
  src/pages/insurance/InsuranceDetail.tsx
  src/routes/CashWalkPages.tsx
Labels: FEAT, 우영

#30 [FEAT] 데이터 타입 지정 및 컴포넌트 분리
  index.html
  package-lock.json
  package.json
  src/components/Button/index.tsx
  src/pages/Login/loginForm.tsx
  src/pages/Signup/AccountCover.tsx
  src/pages/Signup/AccountRegistration.tsx
  src/pages/Signup/AnimalCheck.tsx
  src/pages/Signup/AnimalInfo.tsx
  src/pages/Signup/Signup.tsx
  src/pages/Signup/SignupSuccess.tsx
  src/routes/SignupPages.tsx
  src/store/UseUserStore.tsx
Labels: FEAT, 채린

#34 [FEAT] targets API 연결
  package-lock.json
  package.json
  src/api/APIconfig.ts
  src/api/investAPI.ts
  src/components/Card/GoalCard.tsx
  src/main.tsx
  src/pages/investPet/Deposit.tsx
  src/pages/investPet/InvestPet.tsx
  src/pages/investPet/SavingsGoal.tsx
  src/pages/investPet/TotalSpent.tsx
Labels: FEAT, 우영

#35 [FEAT] 마이페이지 api 연결
  package-lock.json
  package.json
  src/api/userAPI.ts
  src/pages/Account/AccountInfo.tsx
  src/pages/Login/loginForm.tsx
  src/pages/Main/index.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Signup/AnimalCheck.tsx
  src/utils/calcDate.ts
Labels: FEAT, 채린

#37 [FEAT] 반려동물 투자하기 api 연결
  src/api/APIconfig.ts
  src/api/chatbotAPI.ts
  src/api/investAPI.ts
  src/components/Card/GoalCard.tsx
  src/pages/ChatBot/ChatBot.tsx
  src/pages/Main/index.tsx
  src/pages/investPet/Deposit.tsx
  src/pages/investPet/InvestPet.tsx
  src/pages/investPet/SavingsGoal.tsx
  src/pages/investPet/TotalSpent.tsx
Labels: FEAT, 우영

#39 [FEAT] 송금관련 API 연결
  src/api/investAPI.ts
  src/api/userAPI.ts
  src/pages/Payment/PayMoney.tsx
  src/pages/Payment/Payment.tsx
  src/pages/Signup/AccountCheck.tsx
  src/pages/Signup/AccountCover.tsx
  src/pages/Signup/AccountRegistration.tsx
  src/pages/Signup/AnimalCheck.tsx
  src/routes/SignupPages.tsx
  src/store/UseUserStore.tsx
Labels: FEAT, 채린

#41 [FEAT] 보험 상품 api 개발
  src/api/cashwalkAPI.ts
  src/api/chatbotAPI.ts
  src/api/insuranceAPI.ts
  src/api/investAPI.ts
  src/components/Card/GoalCard.tsx
  src/pages/CashWalk/CalendarView.tsx
  src/pages/CashWalk/Write.tsx
  src/pages/ChatBot/ChatBot.tsx
  src/pages/Main/index.tsx
  src/pages/insurance/Insurance.tsx
Labels: FEAT, 우영

#42 [FIX] 빌드 오류 해결
  src/api/APIconfig.ts
  src/api/cashwalkAPI.ts
  src/api/insuranceAPI.ts
  src/api/investAPI.ts
  src/components/Card/GoalCard.tsx
  src/pages/Account/AccountData.tsx
  src/pages/Account/AccountInfo.tsx
  src/pages/CashWalk/CalendarView.tsx
  src/pages/CashWalk/CashWalk.tsx
  src/pages/CashWalk/Write.tsx
  src/pages/ChatBot/ChatBot.tsx
  src/pages/Signup/AccountCover.tsx
  src/pages/Signup/AnimalInfo.tsx
  src/pages/Signup/Signup.tsx
  src/pages/insurance/Insurance.tsx
  src/pages/insurance/InsuranceDetail.tsx
  src/pages/investPet/InvestPet.tsx
  src/pages/investPet/TotalSpent.tsx
Labels: FIX, 채린

#44 [FEAT] 거래 내역 조회 API 연결
  src/components/Card/AccountInfoCard.tsx
  src/pages/Account/AccountInfo.tsx
  src/utils/calcDate.ts
Labels: FEAT, 채린

#48 [FEAT] 보험 api 연결 및 QA
  src/api/insuranceAPI.ts
  src/api/investAPI.ts
  src/components/Card/InsuranceCard.tsx
  src/pages/insurance/Insurance.tsx
  src/pages/insurance/InsuranceDetail.tsx
  src/pages/investPet/InvestPet.tsx
Labels: FEAT, 우영

#51 [FEAT] api 연결 및 QA
  src/App.tsx
  src/api/investAPI.ts
  src/api/userAPI.ts
  src/components/Card/AccountInfoCard.tsx
  src/components/Card/GoalCard.tsx
  src/components/Routing/PrivateRoute.tsx
  src/components/Topbar/index.tsx
  src/index.css
  src/pages/Main/index.tsx
  src/pages/investPet/InvestPet.tsx
  src/routes/AccountPages.tsx
  src/routes/CashWalkPages.tsx
  src/routes/InsurancePages.tsx
  src/routes/InvestPages.tsx
  src/routes/MyPages.tsx
  src/routes/PaymentPages.tsx
Labels: FEAT, 우영

#53 [FIX] QA - 탑바, 라우팅, 보험상품 이미지
  src/assets/insuranceLogo/hyundai.png
  src/assets/insuranceLogo/meritz.jpg
  src/assets/insuranceLogo/samsung.png
  src/components/Card/InsuranceCard.tsx
  src/components/Topbar/index.tsx
  src/pages/Main/index.tsx
  src/pages/insurance/Insurance.tsx
  src/pages/insurance/InsuranceDetail.tsx
  src/routes/SignupPages.tsx
Labels: FEAT, 우영

#54 [FIX] 회원 가입 플로우 QA 및 입력 예외 처리
  src/api/userAPI.ts
  src/components/Button/index.tsx
  src/pages/Main/index.tsx
  src/pages/Payment/PayMoney.tsx
  src/pages/Payment/Payment.tsx
  src/pages/Signup/AccountCover.tsx
  src/pages/Signup/AnimalCheck.tsx
  src/pages/Signup/AnimalInfo.tsx
  src/pages/Signup/Signup.tsx
  src/pages/investPet/Deposit.tsx
  src/pages/investPet/InvestPet.tsx
  src/pages/investPet/SavingsGoal.tsx
Labels: FIX, 채린

#57 [FIX] 이미지, 날짜 QA
  src/assets/bankLogo/k.png
  src/assets/bankLogo/sc.png
  src/assets/bankLogo/shinhan.png
  src/assets/bankLogo/광주.jpeg
  src/assets/bankLogo/국민.png
  src/assets/bankLogo/기업.png
  src/assets/bankLogo/농협.png
  src/assets/bankLogo/대구.png
  src/assets/bankLogo/부산.png
  src/assets/bankLogo/우리.png
  src/assets/bankLogo/전북.png
  src/assets/bankLogo/제주.png
  src/assets/bankLogo/토스.webp
  src/assets/bankLogo/하나.png
  src/assets/bankLogo/한국.jpg
  src/assets/bankLogo/한국.png
  src/components/Card/GoalCard.tsx
  src/pages/Account/AccountInfo.tsx
  src/pages/Main/index.tsx
  src/pages/Payment/Payment.tsx
  src/pages/investPet/InvestPet.tsx
  src/pages/investPet/SavingsGoal.tsx
Labels: FIX, 우영

#58 [FIX] 로그인 회원가입 이메일 검사 및 컴포넌트 수정
  src/api/userAPI.ts
  src/components/Topbar/index.tsx
  src/pages/Account/AccountData.tsx
  src/pages/CashWalk/CalendarView.tsx
  src/pages/CashWalk/CashWalk.tsx
  src/pages/CashWalk/Write.tsx
  src/pages/ChatBot/ChatBot.tsx
  src/pages/Login/loginForm.tsx
  src/pages/Main/index.tsx
  src/pages/Mypage/UpdateAnimalInfo.tsx
  src/pages/Payment/PayMoney.tsx
  src/pages/Signup/AccountCheck.tsx
  src/pages/Signup/AccountCover.tsx
  src/pages/Signup/AccountRegistration.tsx
  src/pages/Signup/AnimalCheck.tsx
  src/pages/Signup/AnimalInfo.tsx
  src/pages/Signup/Signup.tsx
  src/pages/insurance/InsuranceDetail.tsx
  src/pages/investPet/Deposit.tsx
  src/pages/investPet/InvestPet.tsx
  src/pages/investPet/SavingsGoal.tsx
  src/pages/investPet/TotalSpent.tsx
  src/routes/InvestPages.tsx
  src/routes/SignupPages.tsx
Labels: FIX, 채린

#61 [FIX] pre
  src/pages/Account/AccountInfo.tsx
  src/pages/Payment/Payment.tsx
Labels: FIX, 우영

#62 [FIX] 빌드용
  src/pages/Account/AccountInfo.tsx
  src/pages/Payment/Payment.tsx
  src/pages/insurance/Insurance.tsx
Labels: FIX, 우영

#63 [FEAT] 계좌 연결 뷰 생성
  src/api/accountAPI.ts
  src/api/investAPI.ts
  src/assets/bankLogo/sc.png
  src/assets/bankLogo/기업.png
  src/assets/bankLogo/농협.png
  src/assets/bankLogo/대구.png
  src/assets/bankLogo/우리.png
  src/assets/bankLogo/제주.png
  src/assets/bankLogo/토스.jpg
  src/assets/bankLogo/토스.webp
  src/assets/bankLogo/한국.jpg
  src/assets/bankLogo/한국.png
  src/components/Navbar/index.tsx
  src/pages/Account/AccountData.tsx
  src/pages/Account/AccountInfo.tsx
  src/pages/Main/index.tsx
  src/pages/Mypage/MyAccount.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Mypage/UpdateCover.tsx
  src/pages/insurance/Insurance.tsx
  src/routes/LoginPages.tsx
  src/routes/MyPages.tsx
  src/routes/SignupPages.tsx
  vite.config.ts
Labels: FEAT, 채린

#65 [FEAT] 뷰 생성, 로티, QA
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/blueStick.png
  src/components/Card/GoalCard.tsx
  src/lotties/congrats.json
  src/lotties/logindog.json
  src/pages/CashWalk/CashWalk.tsx
  src/pages/ChatBot/ChatBot.tsx
  src/pages/Login/login.tsx
  src/pages/Main/Tutorial.tsx
  src/pages/Signup/SignupSuccess.tsx
  src/pages/insurance/Insurance.tsx
  src/pages/investPet/Complete.tsx
  src/pages/investPet/InvestPet.tsx
  src/pages/investPet/TotalSpent.tsx
  src/utils/CongratsLottie.tsx
  src/utils/HomeLottie1.tsx
  src/utils/HomeLottie2.tsx
  src/utils/HomeLottie3.tsx
  src/utils/LoginLottie.tsx
Labels: FEAT, 우영

#66 [FEAT] 데이터 분석 페이지 API 연결
  src/components/Card/AccountInfoCard.tsx
  src/pages/Account/AccountData.tsx
  src/pages/Account/AccountInfo.tsx
  src/pages/Account/Chart.tsx
  src/pages/Main/Tutorial.tsx
  src/utils/calcDate.ts
Labels: FIX, 채린
